# Generated by Django 2.2.5 on 2019-11-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucao',
            name='id_usuario',
            field=models.CharField(max_length=150),
        ),
    ]
