# Generated by Django 2.2.5 on 2019-10-21 00:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.UUIDField(default=uuid.UUID('95f6df43-f030-4eb4-a840-7030493b7caf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
