# Generated by Django 2.2.5 on 2019-11-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.CharField(default='65209c281b104e87a5efa5d9c35ea8c2', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
