# Generated by Django 2.2.5 on 2019-10-21 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20191020_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.UUIDField(default=uuid.UUID('92488c85-a4bc-4ab4-8fe3-60616893bd31'), editable=False, primary_key=True, serialize=False),
        ),
    ]
