# Generated by Django 2.2.5 on 2019-10-27 18:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20191026_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.UUIDField(default=uuid.UUID('a79563a0-8423-43e3-b75e-115b42eb146f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
