# Generated by Django 2.2.5 on 2019-11-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20191117_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.CharField(default='e7be0d8b45424926aa65f7e276fe70b0', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
