# Generated by Django 2.2.5 on 2019-10-27 22:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20191027_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.UUIDField(default=uuid.UUID('c0d22574-6ad4-46ed-b15c-ea72a00f4264'), editable=False, primary_key=True, serialize=False),
        ),
    ]
