# Generated by Django 2.2.5 on 2019-10-27 23:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20191027_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.UUIDField(default=uuid.UUID('17522d75-5e09-422a-87c8-a47d0a68e771'), editable=False, primary_key=True, serialize=False),
        ),
    ]
