# Generated by Django 2.2.5 on 2019-10-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20191027_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.CharField(default='504d1a56651b4fb0b02bc80c3f8b09c4', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
