# Generated by Django 2.2.5 on 2019-10-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20191027_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_logged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.CharField(default='73f9b5c7b0ac422f9b8a77713ca3c7a5', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
