# Generated by Django 2.2.5 on 2019-10-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_auto_20191027_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='agencia',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='banco',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='conta',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.CharField(default='9f205d936ce4453c8fc495534b4bb420', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
