# Generated by Django 2.2.5 on 2019-10-30 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_auto_20191030_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.CharField(default='0b7d65a8c80c4dda92e4575702137797', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
