# Generated by Django 2.2.5 on 2019-11-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='id_pagador',
            field=models.CharField(default='', max_length=150),
        ),
    ]
