# Generated by Django 2.2.5 on 2019-11-17 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='token',
        ),
    ]
