# Generated by Django 2.2.5 on 2019-10-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0002_auto_20191027_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='token',
            field=models.CharField(default='xxxx', max_length=4),
        ),
    ]
