# Generated by Django 2.2.5 on 2019-10-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0003_pagamento_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='id_pagador',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='id_receptor',
            field=models.CharField(default='', max_length=150),
        ),
    ]
