# Generated by Django 2.2.5 on 2019-10-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='servico_id',
            field=models.CharField(default='<function uuid4 at 0x03855030>', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
