# Generated by Django 2.2.5 on 2019-11-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='id_servico',
            field=models.CharField(default='5af8449c1ac74ecf93f2e512345f7d94', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
