# Generated by Django 2.2.5 on 2019-11-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='id_servico',
            field=models.CharField(default='184298e429884f5386a8dc2bf39270f3', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servico',
            name='id_usuario',
            field=models.CharField(max_length=15),
        ),
    ]
