# Generated by Django 2.2.5 on 2019-11-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0004_auto_20191117_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='id_servico',
            field=models.CharField(default='fed8c565eb13447986aac3ee8cc904ae', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
