# Generated by Django 2.2.5 on 2019-10-21 00:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0004_auto_20191020_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='servico_id',
            field=models.CharField(default=uuid.UUID('2df39322-e6f3-4dfb-9827-f235e9fdac3a'), editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
