# Generated by Django 2.2.5 on 2019-10-21 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0005_auto_20191020_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='user_id',
            new_name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='servico_id',
        ),
        migrations.AddField(
            model_name='servico',
            name='id_servico',
            field=models.CharField(default=uuid.UUID('a39c5f71-f72e-4bbc-9eb9-b62b03420053'), editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
