# Generated by Django 2.2.5 on 2019-10-26 20:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0006_auto_20191020_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='id_servico',
            field=models.CharField(default=uuid.UUID('b67039b0-2983-43ac-9fac-e38d383e976a'), editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
