# Generated by Django 2.2.5 on 2019-10-27 23:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0009_auto_20191027_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='id_servico',
            field=models.CharField(default=uuid.UUID('dddde6cd-5184-4bc0-8595-d26ba5e5ca82'), editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
