# Generated by Django 2.2.5 on 2019-10-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0010_auto_20191027_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='id_servico',
            field=models.CharField(default='984df72b2d9e44f3b96246388260b1b8', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
