# Generated by Django 2.2.5 on 2019-10-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0011_auto_20191027_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='id_servico',
            field=models.CharField(default='021c40625a9f4f30b6536eec74be1fbb', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servico',
            name='id_usuario',
            field=models.CharField(max_length=15),
        ),
    ]
