# Generated by Django 2.2.5 on 2019-10-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0012_auto_20191027_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='id_servico',
            field=models.CharField(default='95c677067525465485bc0c8bb6eebcbf', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
