# Generated by Django 2.2.5 on 2019-10-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='credito_id',
            field=models.CharField(default='86ea0b6d-3847-4973-a125-5e7c7f483d06', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
