# Generated by Django 2.2.5 on 2019-11-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='credito_id',
            field=models.CharField(default='c17c27cb-6aaf-4f0f-ac06-d51764c46e74', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
