# Generated by Django 2.2.5 on 2019-11-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0002_auto_20191116_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='credito_id',
            field=models.CharField(default='934b47e4-79c5-4d91-b129-717f1fee90d8', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
