# Generated by Django 2.2.5 on 2019-10-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0002_auto_20191019_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='credito_id',
            field=models.CharField(default='8dc7e4ee-2558-4244-aafd-5963de90ca4e', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
