# Generated by Django 2.2.5 on 2019-11-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0003_auto_20191116_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='credito_id',
            field=models.CharField(default='661c5ed4-24e9-4bee-952d-47fd2770f9e1', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
