# Generated by Django 2.2.5 on 2019-11-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0004_auto_20191117_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='credito_id',
            field=models.CharField(default='a9b1f1fd-418c-4e54-8a96-4b1a6637c8ee', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
