# Generated by Django 2.2.5 on 2019-10-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0005_auto_20191020_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='credito_id',
            field=models.CharField(default='37156b80-6c6a-49bf-8d93-1a69e72dc8a7', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
