# Generated by Django 2.2.5 on 2019-10-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0006_auto_20191020_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='credito_id',
            field=models.CharField(default='e8f46af4-1fc8-4516-98e6-478e8457f273', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
