# Generated by Django 2.2.5 on 2019-10-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0008_auto_20191027_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='credito_id',
            field=models.CharField(default='fb711383-2581-46a3-9836-a001d66d9c85', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
