# Generated by Django 2.2.5 on 2019-10-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0010_auto_20191027_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='credito_id',
            field=models.CharField(default='9657e17a-ad7d-4121-83c3-d954a118b77f', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
