# Generated by Django 2.2.5 on 2019-10-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0011_auto_20191027_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='credito_id',
            field=models.CharField(default='802d8e00-3374-46f6-820c-eac3503e5644', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
