# Generated by Django 2.2.5 on 2019-10-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0013_auto_20191030_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='credito_id',
            field=models.CharField(default='9a8aa0f6-c9e7-4405-b01c-91cfc0f0bba4', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
