# Generated by Django 2.2.5 on 2019-10-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0014_auto_20191030_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='credito_id',
            field=models.CharField(default='2f68e497-90a4-499e-bf97-a8b115b90df4', editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
